from typing import Protocol
from uuid import UUID

from src.modules.intelligence.domain.entities import DocumentExtractedField, DocumentExtraction


class DocumentExtractionRepository(Protocol):
    async def get_by_id(self, extraction_id: UUID) -> DocumentExtraction | None: ...
    async def list_for_document(self, document_id: UUID) -> list[DocumentExtraction]: ...
    async def add(self, extraction: DocumentExtraction) -> None: ...
    async def save(self, extraction: DocumentExtraction) -> None: ...


class DocumentExtractedFieldRepository(Protocol):
    async def list_for_extraction(self, extraction_id: UUID) -> list[DocumentExtractedField]: ...
    async def add_many(self, fields: list[DocumentExtractedField]) -> None: ...
    async def update_value(
        self, *, extraction_id: UUID, field_name: str, field_value: str | None, source: str
    ) -> None: ...
