from typing import Protocol
from uuid import UUID

from src.modules.drivepass.vehicles.domain.entities import Vehicle


class VehicleRepository(Protocol):
    async def get_by_id(self, vehicle_id: UUID) -> Vehicle | None: ...

    async def get_active_by_user_and_plate(
        self, *, user_id: UUID, plate: str
    ) -> Vehicle | None: ...

    async def list_for_user(self, user_id: UUID) -> list[Vehicle]: ...

    async def get_favorite_for_user(self, user_id: UUID) -> Vehicle | None: ...

    async def add(self, vehicle: Vehicle) -> None: ...

    async def save(self, vehicle: Vehicle) -> None: ...

    async def soft_delete(self, vehicle: Vehicle) -> None: ...
