from typing import Protocol
from uuid import UUID

from src.modules.public_access.domain.entities import PublicSession


class PublicSessionRepository(Protocol):
    async def get_by_id(self, session_id: UUID) -> PublicSession | None: ...
    async def get_by_token_hash(self, token_hash: str) -> PublicSession | None: ...
    async def add(self, session: PublicSession) -> None: ...
    async def save(self, session: PublicSession) -> None: ...
    async def revoke_all_for_access(self, vehicle_public_access_id: UUID) -> None: ...
    async def expire_stale(self) -> int: ...
