from typing import Protocol
from uuid import UUID

from src.modules.public_access.domain.entities import VehiclePublicAccess


class PublicAccessRepository(Protocol):
    async def get_by_id(self, access_id: UUID) -> VehiclePublicAccess | None: ...
    async def get_by_vehicle_id(self, vehicle_id: UUID) -> VehiclePublicAccess | None: ...
    async def get_by_public_token(self, public_token: str) -> VehiclePublicAccess | None: ...
    async def add(self, access: VehiclePublicAccess) -> None: ...
    async def save(self, access: VehiclePublicAccess) -> None: ...
