"""create platform core tables

Revision ID: 520bbba97982
Revises: f7bf599fbbf4
Create Date: 2026-06-28 23:33:31.551041
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '520bbba97982'
down_revision: str | None = 'f7bf599fbbf4'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('scope', sa.Enum('GLOBAL', 'MODULE', 'USER', name='feature_flag_scope'), nullable=False),
    sa.Column('module_code', sa.Enum('DRIVE_PASS', 'HOME_PASS', 'PET_PASS', 'HEALTH_PASS', 'FAMILY_PASS', name='module_code'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_key'), 'feature_flags', ['key'], unique=True)
    op.create_table('platform_modules',
    sa.Column('code', sa.Enum('DRIVE_PASS', 'HOME_PASS', 'PET_PASS', 'HEALTH_PASS', 'FAMILY_PASS', name='module_code'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('route_path', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'COMING_SOON', 'DEPRECATED', name='module_status'), nullable=False),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_modules_code'), 'platform_modules', ['code'], unique=True)
    op.create_index(op.f('ix_platform_modules_status'), 'platform_modules', ['status'], unique=False)
    op.create_table('platform_settings',
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_settings_key'), 'platform_settings', ['key'], unique=True)
    op.create_table('user_modules',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ENABLED', 'DISABLED', name='user_module_status'), nullable=False),
    sa.Column('enabled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['platform_modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module_id', name='uq_user_modules_user_module')
    )
    op.create_index(op.f('ix_user_modules_status'), 'user_modules', ['status'], unique=False)
    op.create_index(op.f('ix_user_modules_user_id'), 'user_modules', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_modules_user_id'), table_name='user_modules')
    op.drop_index(op.f('ix_user_modules_status'), table_name='user_modules')
    op.drop_table('user_modules')
    op.drop_index(op.f('ix_platform_settings_key'), table_name='platform_settings')
    op.drop_table('platform_settings')
    op.drop_index(op.f('ix_platform_modules_status'), table_name='platform_modules')
    op.drop_index(op.f('ix_platform_modules_code'), table_name='platform_modules')
    op.drop_table('platform_modules')
    op.drop_index(op.f('ix_feature_flags_key'), table_name='feature_flags')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###
