"""make vehicle_documents unique constraint partial on deleted_at

Revision ID: 642b327554ca
Revises: b5842c565de8
Create Date: 2026-06-29 02:58:18.077782
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '642b327554ca'
down_revision: str | None = 'b5842c565de8'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_vehicle_documents_vehicle_type'), 'vehicle_documents', type_='unique')
    op.create_index('uq_vehicle_documents_vehicle_type', 'vehicle_documents', ['vehicle_id', 'document_type'], unique=True, postgresql_where='deleted_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_vehicle_documents_vehicle_type', table_name='vehicle_documents', postgresql_where='deleted_at IS NULL')
    op.create_unique_constraint(op.f('uq_vehicle_documents_vehicle_type'), 'vehicle_documents', ['vehicle_id', 'document_type'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
