"""create vehicle_documents and document_versions tables

Revision ID: b5842c565de8
Revises: d45eaeda87ce
Create Date: 2026-06-29 02:24:18.741230
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b5842c565de8'
down_revision: str | None = 'd45eaeda87ce'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_documents',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('PADRON', 'SOAP', 'REVISION_TECNICA', 'CERTIFICADO_GASES', 'CERTIFICADO_HOMOLOGACION', 'PERMISO_CIRCULACION', 'SEGURO_PARTICULAR', 'LICENCIA_CONDUCIR', name='document_type'), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('MISSING', 'UPLOADED', 'VALID', 'EXPIRING_SOON', 'EXPIRED', 'REJECTED', 'NOT_APPLICABLE', name='document_status'), nullable=False),
    sa.Column('visibility', sa.Enum('PRIVATE', 'OWNER_ONLY', 'PUBLIC_AFTER_PIN', name='document_visibility'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'document_type', name='uq_vehicle_documents_vehicle_type')
    )
    op.create_index(op.f('ix_vehicle_documents_document_type'), 'vehicle_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_vehicle_documents_status'), 'vehicle_documents', ['status'], unique=False)
    op.create_index(op.f('ix_vehicle_documents_vehicle_id'), 'vehicle_documents', ['vehicle_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_bucket', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['vehicle_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_number', name='uq_document_versions_document_number')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_versions_is_current'), 'document_versions', ['is_current'], unique=False)
    op.create_index(op.f('ix_document_versions_uploaded_at'), 'document_versions', ['uploaded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_versions_uploaded_at'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_is_current'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_vehicle_documents_vehicle_id'), table_name='vehicle_documents')
    op.drop_index(op.f('ix_vehicle_documents_status'), table_name='vehicle_documents')
    op.drop_index(op.f('ix_vehicle_documents_document_type'), table_name='vehicle_documents')
    op.drop_table('vehicle_documents')
    # ### end Alembic commands ###
