"""create vehicles table

Revision ID: d45eaeda87ce
Revises: 520bbba97982
Create Date: 2026-06-29 01:39:19.557661
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd45eaeda87ce'
down_revision: str | None = '520bbba97982'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plate', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('vin', sa.String(length=32), nullable=True),
    sa.Column('engine_number', sa.String(length=64), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('fuel_type', sa.Enum('GASOLINE', 'DIESEL', 'HYBRID', 'ELECTRIC', 'UNKNOWN', name='vehicle_fuel_type'), nullable=False),
    sa.Column('transmission', sa.Enum('MANUAL', 'AUTOMATIC', 'CVT', 'UNKNOWN', name='vehicle_transmission'), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='vehicle_status'), nullable=False),
    sa.Column('nfc_uuid', sa.UUID(), nullable=True),
    sa.Column('public_pin_hash', sa.String(length=255), nullable=True),
    sa.Column('public_enabled', sa.Boolean(), nullable=False),
    sa.Column('vehicle_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vehicles_favorite', 'vehicles', ['favorite'], unique=False)
    op.create_index('ix_vehicles_plate', 'vehicles', ['plate'], unique=False)
    op.create_index(op.f('ix_vehicles_status'), 'vehicles', ['status'], unique=False)
    op.create_index(op.f('ix_vehicles_user_id'), 'vehicles', ['user_id'], unique=False)
    op.create_index('uq_vehicles_active_user_plate', 'vehicles', ['user_id', 'plate'], unique=True, postgresql_where="status = 'ACTIVE' AND deleted_at IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_vehicles_active_user_plate', table_name='vehicles', postgresql_where="status = 'ACTIVE' AND deleted_at IS NULL")
    op.drop_index(op.f('ix_vehicles_user_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_status'), table_name='vehicles')
    op.drop_index('ix_vehicles_plate', table_name='vehicles')
    op.drop_index('ix_vehicles_favorite', table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
