from datetime import UTC, datetime, timedelta
from uuid import UUID, uuid4

from src.domain.base import Entity
from src.modules.public_access.domain.value_objects import SessionStatus

SESSION_DURATION_MINUTES = 10


class PublicSession(Entity):
    """A short-lived anonymous session created after a successful PIN entry.

    The raw session token is generated by `PublicSessionService` and returned
    to the client once — only the SHA-256 hash is stored here.  Sessions last
    `SESSION_DURATION_MINUTES` (10 minutes) and can be revoked explicitly
    (e.g. when the public token is regenerated)."""

    def __init__(
        self,
        *,
        id: UUID,
        vehicle_public_access_id: UUID,
        session_token_hash: str,
        expires_at: datetime,
        ip_address: str | None,
        user_agent: str | None,
        created_at: datetime,
        revoked_at: datetime | None,
    ) -> None:
        super().__init__(id)
        self.vehicle_public_access_id = vehicle_public_access_id
        self.session_token_hash = session_token_hash
        self.expires_at = expires_at
        self.ip_address = ip_address
        self.user_agent = user_agent
        self.created_at = created_at
        self.revoked_at = revoked_at

    @classmethod
    def create(
        cls,
        *,
        vehicle_public_access_id: UUID,
        session_token_hash: str,
        duration_minutes: int = SESSION_DURATION_MINUTES,
        ip_address: str | None = None,
        user_agent: str | None = None,
    ) -> "PublicSession":
        now = datetime.now(UTC)
        return cls(
            id=uuid4(),
            vehicle_public_access_id=vehicle_public_access_id,
            session_token_hash=session_token_hash,
            expires_at=now + timedelta(minutes=duration_minutes),
            ip_address=ip_address,
            user_agent=user_agent,
            created_at=now,
            revoked_at=None,
        )

    @property
    def status(self) -> SessionStatus:
        if self.revoked_at is not None:
            return SessionStatus.REVOKED
        if self.expires_at <= datetime.now(UTC):
            return SessionStatus.EXPIRED
        return SessionStatus.ACTIVE

    def is_valid(self) -> bool:
        return self.status == SessionStatus.ACTIVE

    def revoke(self) -> None:
        self.revoked_at = datetime.now(UTC)
